api7/lua-resty-etcd

- lib/resty/etcd.lua
- t/invalid-value.t
> bugfix: returned error message if there was invalid value instead of

- .travis.yml
- Makefile
- README.md
- lib/resty/etcd.lua
- lib/resty/etcd/utils.lua
- lib/resty/etcd/v2.lua
- lib/resty/etcd/v3.lua
- rockspec/lua-resty-etcd-0.8-0.rockspec
- rockspec/lua-resty-etcd-dev-0.1-0.rockspec
- t/Procfile-single
- t/Procfile-single-enable-v2
- t/cluster.t
- t/dir.t
- t/key.t
- t/normalize.t
- t/v3.t
> feat: support etcd v3 protocol.

- lib/resty/etcd/v3.lua
- t/v3/key.t
1. fix watchdir delete not work
2. fix readdir kv.key not decode_base64
> fix watchdir delete not work

- .travis.yml
- lib/resty/etcd.lua
- lib/resty/etcd/v3.lua
- t/v2/add-auth.sh
- t/v2/cluster.t
- t/v3/add-auth.sh
- t/v3/cluster.t
- t/v3/key.t
1.  add etcdv3 auth (support etcd 3.3+)
2.  update v2 and v3 cluster testcase
3. fix v3 cluster host bug
> add auth v3

- api_v2.md
- api_v3.md
- lib/resty/etcd.lua
- lib/resty/etcd/utils.lua
- lib/resty/etcd/v2.lua
- lib/resty/etcd/v3.lua
- t/v2/key.t
make api prefix and key prefix clear.
add prefix on key before invoke key api.
> prefix issue

- lib/resty/etcd/v2.lua
> fix: return original error

- api_v3.md
prototol  spell error, will make the demo run on v2
> api_v3.md prototol ->protocol

- README.md
- lib/resty/etcd/utils.lua
- lib/resty/etcd/v3.lua
- t/v2/dir.t
- t/v2/key.t
- t/v3/key.t
fix etcd v3 watch dir bug
add watch key="" empty case, mean watch all key change
> fix etcd v3 watch dir bug

- lib/resty/etcd/utils.lua
- lib/resty/etcd/v3.lua
- t/normalize.t
- t/v2/dir.t
fix watch body has '\n', cause `json decode err` bug
> fix watch body has '\n', cause `json decode err` bug

- .gitignore
- .travis.yml
- Makefile
- api_v3.md
- lib/resty/etcd/utils.lua
- lib/resty/etcd/v3.lua
- utils/check-lua-code-style.sh
> feature: add lint check

- Makefile
- README.md
- api_v3.md
1. supplement for #73 
2. fix make dev typo
> fix: add doc for watchcancel

- .travis.yml
- t/v2/dir.t
> ci: make CI pass under OpenResty 1.19

- README.md
> chore: correct install by source instruction order

- api_v3.md
* several grammar corrections
* change them for better reading
> chore: several grammar corrections to api v3 doc

- rockspec/lua-resty-etcd-1.4.4-0.rockspec
> build: release version v1.4.4

- .github/workflows/ci.yml
- t/v2/dir.t
- t/v3/lease.t
> test: revoke keepalived lease, to avoid effect to other test

- rockspec/lua-resty-etcd-1.5.1-0.rockspec
> feat: release v1.5.1

- rockspec/lua-resty-etcd-1.5.3-0.rockspec
@membphis Sorry I found a bug in the last commit so we need another new release
> feat: release v1.5.3

- rockspec/lua-resty-etcd-1.5.5-0.rockspec
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> feat: release v1.5.5

- api_v3.md
- lib/resty/etcd/v3.lua
- t/v3/sni.t
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> feat: adding custom SNI for etcd TLS requests

- lib/resty/etcd/v3.lua
- t/v3/sni.t
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> chore: adjust pass SNI in the request chunk

- .github/workflows/ci.yml
- health_check.md
- lib/resty/etcd/health_check.lua
- lib/resty/etcd/v3.lua
- t/v3/auth.t
- t/v3/health_check.t
- t/v3/mtls.t
> feat: passive round-robin health check

- lib/resty/etcd/v3.lua
There is a race that some endpoints may be retried twice because
the previous health status is override during the health check
mode changes to shm.
> fix: the returned result may be nil when max retry is exceeded

- lib/resty/etcd/v3.lua
- t/v3/key.t
see https://github.com/apache/apisix/pull/6892
> fix: the last chunk containing only newlines will cause a delay in event handling

- lib/resty/etcd/v3.lua
> fix: optimize judgment statements

- rockspec/lua-resty-etcd-1.7.0-0.rockspec
> feat: release v1.7.0

- health_check.md
- lib/resty/etcd/health_check.lua
- t/v3/health_check.t
> feat: allow disabling health check

- rockspec/lua-resty-etcd-1.8.0-0.rockspec
> feat: release v1.8.0

- rockspec/lua-resty-etcd-1.8.1-0.rockspec
> feat: release v1.8.1

- rockspec/lua-resty-etcd-1.8.2-0.rockspec
> feat: release v1.8.2

- rockspec/lua-resty-etcd-1.9.0-0.rockspec
> feat: release v1.9.0

- t/v3/cluster.t
- t/v3/health_check.t
- t/v3/mtls.t
- t/v3/sni.t
- t/v3/tls.t
suppress Use of uninitialized value $enable_tls in string eq
> chore: suppress test warnings

- .github/workflows/ci.yml
- .luacheckrc
- lib/resty/etcd/proto.lua
- lib/resty/etcd/v3.lua
- rockspec/lua-resty-etcd-master-0.1-0.rockspec
- t/v3/grpc/key.t
> feat: add grpc backend for get/set

- lib/resty/etcd/v3.lua
- t/v3/grpc/key.t
> feat: grpc for delete and readdir

- lib/resty/etcd/proto.lua
- lib/resty/etcd/v3.lua
- t/v3/grpc/txn.t
> feat(grpc): add txn/setnx

- lib/resty/etcd/proto.lua
- lib/resty/etcd/v3.lua
- t/v3/grpc/key.t
- t/v3/grpc/lease.t
> feat(grpc): add grant/revoke/keepalive/leases/timetolive

- lib/resty/etcd/v3.lua
- t/v3/grpc/misc.t
> fix: avoid error when loading etcd module in init_by_lua phase

- lib/resty/etcd/v3.lua
- t/v3/grpc/key.t
- t/v3/grpc/txn.t
> fix: be compatible with the usage in APISIX

- .github/workflows/ci.yml
- lib/resty/etcd/v3.lua
- t/v3/grpc/mtls.t
- t/v3/grpc/tls.t
> feat(grpc): add tls support

- lib/resty/etcd/v3.lua
> chore: avoid unwanted data

- rockspec/lua-resty-etcd-1.10.0-0.rockspec
- rockspec/lua-resty-etcd-master-0.1-0.rockspec
> feat: release v1.10.0

- lib/resty/etcd/v3.lua
- t/v3/grpc/key.t
> feat(grpc): support watching dir

- lib/resty/etcd/v3.lua
- t/v3/grpc/misc.t
> feat: add method to close gRPC conn

- rockspec/lua-resty-etcd-1.10.2-0.rockspec
> feat: release v1.10.2

- rockspec/lua-resty-etcd-master-0.1-0.rockspec
> fix: our own fork is not maintained

- rockspec/lua-resty-etcd-1.10.3-0.rockspec
> feat: release v1.10.3
