lib/resty/etcd/utils.lua
lib/resty/etcd/v3.lua

```
local prefix_v3 = {
["3.5."] = "/v3",
["3.4."] = "/v3",
["3.3."] = "/v3beta",
["3.2."] = "/v3alpha",
}
function _M.has_value(arr, val)
for index, value in ipairs(arr) do
if value == val then
return index
end
end
return false
end
```
`prefix_v3` length is 0, so has_value method always return false

fix: utils.has_value method always return false

---

lib/resty/etcd/v3.lua
t/v3/key.t

1.I comment encode_json/decode_json for the data,because I think the api should only support string.And the encode_json/decode_json shoud be done by the API's users (they may wan't use json to serialization)
2.true or false should be boolean
3.the `get` api lost args attr 
4.the body.result may be nil when etcd server error

som bug fix

---

api_v2.md
api_v3.md

doc: replaced `key` with `dir` in dir-API parameters.

---

.luacheckrc
.travis.yml
api_v2.md
lib/resty/etcd.lua
lib/resty/etcd/serializers/json.lua
lib/resty/etcd/serializers/raw.lua
lib/resty/etcd/utils.lua
lib/resty/etcd/v2.lua
lib/resty/etcd/v3.lua
rockspec/lua-resty-etcd-master-0.1-0.rockspec
t/v2/invalid-value.t
t/v2/serializer.t

Currently, lua-resty-etcd only support for json values and string values not in json format will be discard.  https://github.com/api7/lua-resty-etcd/issues/71 and https://github.com/api7/lua-resty-etcd/issues/57 discussed the requirement for the origin string value stored in etcd. This pull request supports the feature by adding a `serializer` option in `new` method to abstract the serialize and deserialize behavior.

feat: support original string value via a serializer option

---

lib/resty/etcd/v3.lua

Currently every operation in etcd v3 would at least add two info level lines to log file, which could make log file a mess in larger project, especially compared to etcd v2 which would not add a single info lever log line. 
Thus I think it could be a good idea to remove unnecessary log output.

fix: remove unnecessary log in etcd v3

---

api_v2.md
api_v3.md
lib/resty/etcd/v3.lua

This bug leads to the TLS certificate verficiation is always enabled.
Since the `etcd.new` first use protocol v2 to fetch the version information where the TLS connection is built normally, and later operations reuse this connection, so the pathological logic in v3 doesn't have a chance to run.

bugfix: fixed the typo "verfiy" to "verify".

---

api_v2.md

Hi, I found a tiny but important doc error in api_v2.md.
There is no *header* field but *headers*, I think it would boring lots of new users.

docs: fix http response desc

---

health_check.md
lib/resty/etcd/health_check.lua
lib/resty/etcd/utils.lua
lib/resty/etcd/v3.lua
rockspec/lua-resty-etcd-master-0.1-0.rockspec
t/v3/health_check.t

feat: endpoint choose by health check

---

lib/resty/etcd/v3.lua
t/v3/health_check.t

fix: directly return an error message when there is no healthy node available

---

api_v3.md

Set `timeout = 0` could not disable timeout, it would turn to use the default `lua_socket_connect_timeout` when we do `tcpsock:settimeout(0)`. Could get that from openresty [test case](https://github.com/openresty/lua-nginx-module/blob/master/t/023-rewrite/tcp-socket-timeout.t#L141-L173).
Ref:
1. https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua#L67
2. https://github.com/openresty/lua-nginx-module/blob/master/t/023-rewrite/tcp-socket-timeout.t#L141-L173

doc: fix explanation when timeout set to zero

---

.github/workflows/release.yml
MAINTAINING.md

Mentioned in #116
I think we could add a Github Actions to automize the version release. It could also work for other repos of api7 that need to upload to luarocks.
The process would be like, whenever we push a new **tag**, it would upload the new release on github and also upload rockspec to luarocks.
**One thing to discuss** is that, do we need to bind the release action to PR, say when we have a release PR tagged with "Release", when it got merged, the action would be triggered to create a tag, and do the rest. 
It would be more convenient, but we need an extra PR when changing release larger change, say from 1.4.3 to 1.5. Ref: https://github.com/anothrNick/github-tag-action
**TODO**

feat: add github actions for release

---

lib/resty/etcd/v3.lua
t/v3/auth.t
t/v3/health_check.t

When running etcd, if etcd node is disconnected, error log would contains
```
2021/02/27 15:30:19 [error] 49#49: *114289 [lua] config_etcd.lua:566: failed to fetch data from etcd: /usr/local/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:593: attempt to index field 'result' (a nil value)
stack traceback:
/usr/local/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:593: in function 'res_func'
/usr/local/apisix/apisix/core/config_etcd.lua:125: in function 'waitdir'
/usr/local/apisix/apisix/core/config_etcd.lua:305: in function 'sync_data'
/usr/local/apisix/apisix/core/config_etcd.lua:540: in function </usr/local/apisix/apisix/core/config_etcd.lua:530>
[C]: in function 'xpcall'
/usr/local/apisix/apisix/core/config_etcd.lua:530: in function …
```

fix: should fail fast when etcd returns error

---

.gitignore
health_check.md
lib/resty/etcd/health_check.lua
lib/resty/etcd/utils.lua
lib/resty/etcd/v3.lua
t/v3/auth.t
t/v3/health_check.t

1. add option `retry` in health-check. When it is enabled, operations would keep trying the same endpoint till unhealthy, and then other endpoints, until success or no endpoints healthy. So we could ensure each operation would send to etcd with best effort.
Currently not support for `read_watch` since it would be better to close the original connection and create a new watch with a new endpoint.
2. move `choose_enpoint` into `request_uri` and `request_chunk` so it could find alternative endpoint easier

feat: support retry in health-check

---

rockspec/lua-resty-etcd-1.5.2-0.rockspec

Remove `description.maintainer` since
> we can remove this line later
_Originally posted by @membphis in https://github.com/api7/lua-resty-etcd/pull/129#discussion_r629813049_

feat: release v1.5.2

---

lib/resty/etcd/v3.lua
t/v3/health_check.t

Just found two bugs related to #131. 
- When no endpoints healthy, we need `#self.endpoints * health_check.conf.max_fails` times to make all endpoints status changed to unhealthy, and it would be better to retry another time to return the error `has no healthy etcd endpoint available` so users could better deal with the result.
- When only one etcd endpoint is set, we still need to enable health_check, to keep "ERR_NO_ETCD_ENDPOINT_AVAILABLE" the same.

fix: etcd should add another retry when no endpoints healthy

---

lib/resty/etcd/v3.lua

Ref #133
Currently we got
```
2021/06/28 16:44:17 [warn] 18038#18038: *5482 [lua] v3.lua:148: grant(): http://127.0.0.1:23790: connection refused. Retrying, context: ngx.timer
2021/06/28 16:44:17 [warn] 18038#18038: *5482 [lua] v3.lua:148: grant(): http://127.0.0.1:23790: connection refused. Retrying, context: ngx.timer
2021/06/28 16:44:17 [warn] 18038#18038: *5482 [lua] health_check.lua:63: report_failure(): update endpoint: http://127.0.0.1:23790 to unhealthy, context: ngx.timer
2021/06/28 16:44:17 [warn] 18038#18038: *5482 [lua] v3.lua:148: grant(): http://127.0.0.1:23790: connection refused. Retrying, context: ngx.timer
2021/06/28 16:44:17 [warn] 18038#18038: *5482 [lua] v3.lua:148: grant(): http://127.0.0.1:23791: connection refused. …
```

chore: remove unnecessary log for health check retry

---

.github/workflows/release.yml
MAINTAINING.md

After #117, to trigger auto release, we still need a maintainer to create a tag. To simplify the steps (so no need to ask membphis each time 😿), try to move trigger from tag to merged PR with changes in rockspec and also title prefix in `feat: release`.
Tested in https://github.com/Yiyiyimu/GithubActionsTest/actions/runs/983995083 and works as expected

ci: refine auto release steps

---

.github/workflows/ci.yml

Signed-off-by: tzssangglass <tzssangglass@gmail.com>

chore(ci): fetch apisix-openresty has been renamed to apisix-base

---

.github/workflows/ci.yml
README.md
lib/resty/etcd/v3.lua
t/v3/key.t

Try to fix #153, we have verified in our environment that can solve that problem, but the test cases still need time to complete.

fix: let etcd v3 `read_watch` handle the case where a chunk contains partial event or multiple events

---

api_v3.md
lib/resty/etcd/v3.lua
t/v3/unix_socket.t

feat: support proxying via unix socket

---

lib/resty/etcd/v3.lua

fix: conn leak when watch timed out

---

.github/workflows/ci.yml
lib/resty/etcd/v3.lua

It will be closed by watchcancel method.

fix: we don't need to close http_cli after reading chunks failed

---

README.md

The travis-ci had no longer been used, So I changed the badge of the continuous integration’s badge.
Signed-off-by: u5surf <u5.horie@gmail.com>

chore: fix CI badge in README.md

---

api_v3.md

The etcd docs on the github’s repo has removed due to https://github.com/etcd-io/etcd/pull/12660.

docs: fix link of etcd api gateway

---

lib/resty/etcd/v3.lua
t/v3/grpc/txn.t

fix: correct the previous test case.

---

t/v3/grpc/txn.t

delete /setnx may return 404 if `/setnx` is not existed.

test: fix flaky test

---

.github/workflows/ci.yml
lib/resty/etcd/v3.lua

error logs:
The cause of the issue is that in the function `refresh_jwt_token`,  the parameter `timeout` of semaphore wait directly uses the parameter passed by the caller without considering that the `timeout` parameter may be nil. If the caller does not pass the parameter `timeout`, this error will be triggered:
The `timeout` passed to the function `refresh_jwt_token` is basically `self.timeout`:
Since the `timeout` passed to the function `refresh_jwt_token` is basically `self.timeout`, we make a judgment on the `timeout` parameter in `refresh_jwt_token`, If it is nil, just use `self.timeout`, if `self.timeout` is nil too, just use 0, to ensure the `timeout` is not nil to avoid the error.

fix: ensure timeout not nil to avoid `attempt to perform arithmetic on a nil value` error
